### PR TITLE
Nonlinearity module implementation

### PR DESCRIPTION
**Pull request by silviamich**
This PR has been created to include nonlinearity in the simulations. An independent module accounting for HWP differential emission is present as well.

### CODE REVIEW

**Comment by ziotom78** [comment]
Hi @silviamich , nice work! I had a look at the code, and I find it very well written. Would you like discuss it at the next LiteBIRD Simulation Telecon?

**Comment by silviamich** [comment]
Thanks @ziotom78, sure I can present it at the next telecon!

**Comment by paganol** [comment]
It think we are ready for merging the PR

**Comment by ziotom78** [comment]
> I think we are ready for merging the PR

I agree, I checked the code and looks great!

**Pull request merged**
