### PR TITLE
Reorganize the User’s manual

### PR DESCRIPTION
**Pull request by ziotom78**
This PR addresses issue #341.

- [X] Use PyData as the default theme for docs and update Sphinx and deps
- [X] Rework the structure of the documentation
- [x] Check that the documentation is consistent and reads seamlessly

### CODE REVIEW

**Comment by ziotom78** [comment]
I have completed fixing the grammar. Could somebody please have a look at the way the documentation looks now? Here is a screenshot with the new style:

image

**Comment by paganol** [comment]
Hi @ziotom78, I like it, thanks!! I just added an example for the high level interface in the noise section. 

I also took the opportunity for changing the default behavior of `Simulation.add_noise`, before we had to pass explicitly the random number generator, now, if random is empty, `self.random` is used. This change doesn't really belong to this PR, so if you think that it should be in a separate PR I can do that, let me know.

https://github.com/litebird/litebird_sim/blob/bcf9cc07ef8977cea3069dc3903967a8ea7ff5f6/litebird_sim/simulations.py#L1549-L1574

**Comment by ziotom78** [comment]
> I also took the opportunity for changing the default behavior of Simulation.add_noise, before we had to pass explicitly the random number generator, now, if random is empty, self.random is used. This change doesn't really belong to this PR, so if you think that it should be in a separate PR I can do that, let me know.

I know it’s boring, but having a separate PR for it would be clearer to users. This would let us properly advertise this change in the CHANGELOG by referencing the right PR.

**Comment by paganol** [comment]
For me we can merge

**Pull request merged**
